version: "3"
services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile-frontend
        container_name: joegames-frontend
        restart: always
        environment:
            - NUXT_HOST=0.0.0.0
            - NODE_ENV=production
        volumes:
          - ./data/:/app/data/
        depends_on:
            - backend
    backend:
        build:
            context: .
            dockerfile: Dockerfile-backend
        container_name: joegames-backend
        restart: always
        environment:
            - MAX_WORKERS=1
    redis:
        image: redis
        container_name: joegames-redis
    nginx:
        image: nginx:latest
        container_name: joegames-nginx
        restart: always
        volumes:
          - ./nginx:/etc/nginx/conf.d
        depends_on:
          - frontend
        environment:  
            - VIRTUAL_HOST=joegames.nodja.com
            - VIRTUAL_PORT=80
        