version: "3.7"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    container_name: joegames-frontend
    restart: always
    environment:
      - NUXT_HOST=0.0.0.0
      - NODE_ENV=production
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.joegames-frontend.entrypoints=web"
      - "traefik.http.routers.joegames-frontend.rule=Host(`joegames.nodja.com`)"
      - "traefik.http.services.joegames-frontend.loadbalancer.server.port=3000"
      
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    container_name: joegames-backend
    restart: always
    environment:
      - MAX_WORKERS=4
    volumes:
      - ./data/:/app/data/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.joegames-backend.entrypoints=web"
      - "traefik.http.routers.joegames-backend.rule=(Host(`joegames.nodja.com`) && PathPrefix(`/api`)) || (Host(`joegames.nodja.com`) && PathPrefix(`/ws`)) || (Host(`joegames.nodja.com`) && PathPrefix(`/socket.io`))"
      - "traefik.http.services.joegames-backend.loadbalancer.server.port=80"

networks:
  default:
    external:
      name: traefik_net